--a)
CREATE TABLE KOMPANIJA(
PIB NUMBER(20) PRIMARY KEY,
NAZIV VARCHAR(50) NOT NULL,
ULICA VARCHAR(50),
BROJ VARCHAR(10),
GRAD VARCHAR(50),
DRZAVA VARCHAR(50)
)

CREATE TABLE ZAPOSLENI(
JMBG VARCHAR(13) PRIMARY KEY,
DAT_RODJ DATE,
LIME VARCHAR(30) NOT NULL,
PREZIME VARCHAR(30) NOT NULL,
SLOVO CHAR(1),
GOD_STAZA NUMBER(3),
PLATA NUMBER(10)
)

CREATE TABLE VOZILO(
ID NUMBER(5) PRIMARY KEY,
KM NUMBER(10),
GODPROIZ NUMBER(4),
DAT_ISTEKA DATE NOT NULL,
GORIVO VARCHAR(20) CHECK(GORIVO IN('DIZEL', 'BENZIN')),
PIBFIR NUMBER(20) REFERENCES KOMPANIJA(PIB)
)
CREATE TABLE PRATI(
DAT_POC DATE NOT NULL,
DAT_KRAJA DATE,
JMBG VARCHAR(13) REFERENCES ZAPOSLENI(JMBG),
ID_VOZILA NUMBER(5) REFERENCES VOZILO(ID),
PRIMARY KEY (JMBG, ID_VOZILA)
)

--Nemam unos :(

--b)
SELECT K.NAZIV, K.DRZAVA, COUNT(V.ID), SUM(KM)
FROM KOMPANIJA K INNER JOIN VOZILO V ON K.PIB=V.PIBFIR
GROUP BY K.NAZIV,K.DRZAVA
HAVING COUNT(V.ID)>=2

--c)
SELECT DISTINCT z.jmbg, z.lime, z.prezime

FROM ZAPOSLENI Z INNER JOIN PRATI P ON Z.JMBG=P.JMBG
INNER JOIN VOZILO V ON V.ID=P.ID_VOZILA
INNER JOIN KOMPANIJA K ON K.PIB=V.PIBFIR

WHERE EXISTS(
    SELECT COUNT(*)
    FROM KOMPANIJA K1
    WHERE K1.PIB=K.PIB
    GROUP BY K1.NAZIV
    HAVING COUNT(*)<5) 
AND NOT EXISTS(
    SELECT *
    FROM VOZILO V1
    WHERE V1.ID=V.ID AND GORIVO LIKE 'DIZEL' AND KM>100000)

--d)
/*PRIMER AKO SE TRAZI U JEDNINI*/
SELECT *
FROM
(
SELECT K.NAZIV, COUNT(V.ID)
FROM KOMPANIJA K INNER JOIN VOZILO V ON K.PIB=V.PIBFIR
INNER JOIN PRATI P ON P.ID_VOZILA=V.ID
WHERE DAT_KRAJA IS NULL
GROUP BY K.NAZIV
ORDER BY COUNT(V.ID)
)
WHERE ROWNUM=1

/*PRIMER AKO SE TRAZI U MNOZINI*/
SELECT K.NAZIV, COUNT(*)
FROM KOMPANIJA K INNER JOIN VOZILO V ON K.PIB=V.PIBFIR
    INNER JOIN PRATI P ON P.ID_VOZILA=V.ID
GROUP BY K.NAZIV
HAVING COUNT(V.ID)=(
    SELECT MIN(BROJVOZILA) 
    FROM(
        SELECT COUNT(V1.ID)"BROJVOZILA"
        FROM VOZILO V1 INNER JOIN PRATI P1 ON V1.ID = P1.ID_VOZILA
        WHERE DAT_KRAJA IS NULL
        GROUP BY V1.PIBFIR
        )
)